theme: jekyll-theme-minimal
title: Serge Sharoff's homepage
description: I am Serge Sharoff, Professor of Language Technology and Digital Humanities at the University of Leeds, UK
google_analytics:
logo: img/sharoff-2009-noflash-face.jpg