#+TITLE: Robust frequency lists
#+AUTHOR: 
#+DATE: 
#+OPTIONS: toc:t

#+begin_quote
  Nothing in Nature is random... A thing appears random only through the
  incompleteness of our knowledge. ---Spinoza, Ethics I
#+end_quote

* Know thy corpus!
  :PROPERTIES:
  :CUSTOM_ID: know-thy-corpus
  :END:
Frequency lists determine the probability estimates for words in
language models.  They are also widely used in lexicography, corpus
linguistics and language education studies. However, word frequency
lists coming from different corpora differ considerably in spite of
relatively small changes in their composition, because some words can
become too frequent in a relatively small number of texts specific to
this corpus, so their frequency counts provide unreliable information
about their expected frequency. Adam Kilgarriff referred to them as
/whelks/, a rare word, which can become topical if a text is about
whelks. The whelks of the British National Corpus (BNC) are medical
terms, as seen in the following two extracts from the BNC frequency
list:

 1. /foods, lighting, sciences, anglo, emerge, contacts, *gastric*, desirable, 1950s, gender, poland, picking, suggestions, enjoying, laughter/
 2. /incidentally, sticking, angrily, speeds, drum, spine, realm, *mucosa*, heather, allegedly, rested, builders, lid, invention, blowing/

where the frequency of /gastric/ is ranked higher than /desirable/ and
/mucosa/ is ranked higher than /builders/. Only a small proportion of
BNC texts are taken from the Journal of Gastroentorology and
Hepatology (this is less than 0.8% of the BNC, 713 thousand
tokens). However, the frequency bursts of words from this domain
propel them into the core lexicon.

No corpus is immune to whelks. For example, the frequency of /Texas/
in the LDC Gigaword corpus is greater than that of such common words
as /long/ or /car/. In the Wikipedia dump, which was used to train BERT, /pomeranian/ is more frequent than /hypothetical/ or /centrally/.

Robust lists for a number of languages and corpora are listed in the
[[#frequency-lists][Frequency lists]] section below.

* Robust methods
  :PROPERTIES:
  :CUSTOM_ID: robust-methods
  :END:
The tools in this repository can produce robust frequency lists by using
document-level measures to filter out frequency bursts using methods
from robust statistics. The method which this study found to be more
useful is based on /huberM/ and /S//n/ estimators of expected values.

In short, we determine robust estimates of how many times a word *is
likely* to occur in a document of this corpus. With this value we clip
(Winsorise) its frequency to our predicted robust estimate if the
frequency exceeds the estimate in the case of a frequency burst in this
document. This helps in describing the frequency distributions from
different corpora by making more reliable predictions of how common the
words and their constructions are, and in inferring the significant
differences in the lexicons of different text collections, e.g.,
detecting problems in a given corpus, how a Web crawl is different from
the BNC, etc. For the rationale and the methodology, see:

#+begin_example
@InProceedings{sharoff20,
  author =   {Serge Sharoff},
  title =    {Know thy corpus! Robust methods for digital curation of Web corpora},
  booktitle = {Proc LREC},
  year =     2020,
  month =    {May},
  address =      {Marseilles}}
#+end_example

[[https://aclanthology.org/2020.lrec-1.298/]]

* Scripts
  :PROPERTIES:
  :CUSTOM_ID: scripts
  :END:
The starting point for building a robust frequency list is a document
level frequency list, e.g.,

#+begin_example
correct 1 8309
correct 1 20116
gastric 1 62338
gastric 17 59681
#+end_example

In this example, /correct/ occurs once in two documents (with the
lengths of 8309 and 20116 words), while /gastric/ occurs once in one
document and 17 times in another one. This is an outlying observation
which can be detected using methods from robust statistics.

A list of this kind is produced by taking a corpus in the form of a
single file with one document per line, e.g.

#+begin_example
... invariably , even when we have needed to correct or update details in our reports ,
... diffuse into the gastric lumen , so the presence of any iron in fasting gastric juice
#+end_example

and running:

=frq-line.py corpus.ol >corpus-doc.num=

If you have access to a computer cluster with many computing nodes,
this list can be produced for a large corpus much faster by running
=split -l XX corpus.ol= first to split the corpus into chunks with a fixed
number of documents (XX), so that the document level frequency lists
can be computed in parallel. After that the separate frequency lists
can be combined by running =sort x*.num >corpus-doc.num=

Finally =robustpython.py= can be used to compute the robust frequency
list:

=xzcat bnc-doc.num.xz | python3 robustpython.py 5 | sort -nsrk3,3 >bnc-clean.num=

The parameter is the document level frequency threshold, i.e., the words
for the frequency list need to occur in at least 5 documents in this
example.

For each word (or another object of counting, such as lemma or n-gram),
=robustpython.py= outputs in tab-separated format: 1. the word
itself, 1. the raw frequency, 2. the adjusted robust frequency value
counted for all documents with Winsorisation, 3. the number of documents
subject to Winsorisation, and 4. the document frequency.  For example, a sample of frequencies from the BNC lists looks like:

 
| Word      | Raw  | Adjusted | Clipped | Total Doc |
|-----------+------+------+-----+------|
| correct   | 6706 | 5500 | 263 | 1925 |
| desirable | 2084 | 1858 | 125 |  975 |
| gastric   | 2085 |  154 |  16 |   70 |

The =Raw= frequency column counts the raw number of occurrences, =Adjusted= is the same count with clipped outlier observations, =Clipped= is the number of documents in which this happened, =Total= is the overall number of documents in which this word occurred in this corpus.

The most significant changes in the frequency list before and after
robust estimation (produced by the Perl script =compare_fq_lists.pl= in
the repository) from the BNC are as follows:

| Word          | Raw   | Robust | LL-score |
|---------------+-------+--------+----------|
| hon           | 10709 | 378    | 2890     |
| lifespan      | 3854  | 110    | 1139     |
| darlington    | 5606  | 426    | 875      |
| inc           | 6584  | 794    | 527      |
| taped         | 4151  | 460    | 389      |
| athelstan     | 1061  | 15     | 385      |
| gastric       | 2085  | 154    | 335      |
| theda         | 838   | 9      | 320      |
| robyn         | 1206  | 46     | 313      |
| middlesbrough | 3620  | 488    | 227      |
| infinitive    | 721   | 22     | 208      |
| jenna         | 668   | 19     | 198      |
| minton        | 760   | 29     | 197      |
| ronni         | 538   | 8      | 193      |
| corbett       | 1541  | 144    | 188      |
| colonic       | 830   | 42     | 183      |
| ...           |       |        |          |
| mucosa        | 1041  | 133    | 74       |

For example, /Athelstan, Darlington/ or /[[http://corpus.leeds.ac.uk/cgi-bin/cqp.pl?q=Theda&c=BNC&t=150][Theda]]
are person names in some of the BNC texts (e.g., from "The remains of the
day" for /Darlington/), while the frequency busts of /Hon/ (which takes
it to the top 1000 most frequent words) is down to long lists like: /The
Princess Margaret, Countess of Snowdon was represented by the *Hon* Mrs
Wills at the Memorial Service for Colonel the *Hon* Sir Gordon Palmer./

For information about the log-likelihood score see
[[http://ucrel.lancs.ac.uk/llwizard.html]]

* Frequency lists
  :PROPERTIES:
  :CUSTOM_ID: frequency-lists
  :END:
** English
   :PROPERTIES:
   :CUSTOM_ID: english
   :END:
*** Lists of word forms:
    :PROPERTIES:
    :CUSTOM_ID: lists-of-word-forms
    :END:
1. [[bnc-clean2.tsv][BNC.]] This  is from the classic [[http://www.natcorp.ox.ac.uk/][British National Corpus.]]
2. [[ukwac-clean2.tsv.xz][ukWac.]] A corpus from the [[https://wacky.sslmit.unibo.it/doku.php][Wacky family.]]
3. [[wiki-en-clean2.tsv.xz][Wikipedia.]]
4. [[openwebtext-clean2.tsv.xz][OpenWebText.]]
   This is a clone of OpenAI's corpus collected from upvoted links
   [[https://github.com/jcpeterson/openwebtext][OpenWebText.]]
5. [[ccnet-en-200-clean2-biwt.tsv.xz][CCNET.]]  This is the English corpus from the Common Crawl cleaned for XLM-R,
   see [[http://www.lrec-conf.org/proceedings/lrec2020/pdf/2020.lrec-1.494.pdf][the paper.]]

** Russian
   :PROPERTIES:
   :CUSTOM_ID: russian
   :END:
Lists of *lemmas* with POS codes:

1. [[ru/rnc-orig.out.lpos-clean2-biwt.tsv.xz][Russian National Corpus.]] You can compare this to the raw RNC frequencies in the classic list of [[http://dict.ruslang.ru/freq.php][Lyashevskaya and Sharoff, 2009.]]
2. [[ru/ruTenTen.vert.xz.lpos-clean2-biwt.tsv.xz][ruTenTen.]] A popular corpus from the [[https://www.sketchengine.eu/rutenten-russian-corpus/][SketchEngine.]]
3. [[ru/ruwac.out.gz.lpos-clean2-biwt.tsv.xz][ruWac.]] A corpus from the [[https://wacky.sslmit.unibo.it/doku.php][Wacky family.]]
4. [[ru/gicr-news.out.xz.lpos-clean2-biwt.tsv.xz][GICR.]] This is the news component of the [[http://www.webcorpora.ru/en/][General Internet Corpus of Russian.]]
5. [[ru/ru-maximus.xz.lpos-clean2-biwt.num.xz][Aranea Maximus.]] A large Aranea Web crawl for Russian, see [[https://link.springer.com/article/10.1007/s10579-020-09487-4][the paper]] describing its properties.
6. [[ru/ccnet-ru-3-100-clean2-biwt.tsv.xz][CCNet-Russian]]. The Russian part of the Common Crawl cleaned for XLM-R,
   see [[http://www.lrec-conf.org/proceedings/lrec2020/pdf/2020.lrec-1.494.pdf][the paper.]]

The POS codes in the Russian National Corpus have not been unified with the remaining corpora. For example, *_s* is the code for nouns in the RNC while it is *_n* in other corpora.

** Wikipedia lists
   :PROPERTIES:
   :CUSTOM_ID: wikipedia-lists
   :END:
Robust frequency filtering helps in removing various artifacts of
Wikipedia processing, e.g., unreasonably frequent /pomeranian, montane,
spurred, substrates, encompassed, italianate, prelate, attaining/ in the
BERT BPE lexicon.

- [[http://corpus.leeds.ac.uk/frqc/robust/wikipedia-ar-robust.tsv][Arabic]]
- [[http://corpus.leeds.ac.uk/frqc/robust/wikipedia-cs-robust.tsv][Czech]]
- [[http://corpus.leeds.ac.uk/frqc/robust/wiki-en-clean2.num][English]]
- [[http://corpus.leeds.ac.uk/frqc/robust/wikipedia-it.tsv][Italian]]
- [[http://corpus.leeds.ac.uk/frqc/robust/wikipedia-pl.tsv][Polish]]
- [[http://corpus.leeds.ac.uk/frqc/robust/wikipedia-ru-robust.tsv][Russian]]
- [[http://corpus.leeds.ac.uk/frqc/robust/wikipedia-uk-robust.tsv][Ukrainian]]

ccnet-en-200-clean2-biwt.tsv.xz

openwebtext-robust-R.tsv.xz
