* In the garden and in the jungle: comparing genres in the BNC and in the Internet

*Serge Sharoff*

The jungle metaphor is quite common in genre studies. The subtitle of
[[http://llt.msu.edu/vol5num3/lee/][David Lee's]] seminal paper on genre
classification is `navigating a path through the BNC jungle'. According
to
[[http://www.kilgarriff.co.uk/Publications/2001-K-CorpLingWAC.txt][Adam
Kilgarriff,]] the BNC is a jungle only when compared to smaller
Brown-type corpora, while it looks more like an English garden when
compared to the Web . A corpus from the web can easily surpass the BNC
in size, see 160 million words of
[[http://wackybook.sslmit.unibo.it/pdfs/sharoff.pdf][I EN]] or 2 billion
words of ukWac ([[http://wacky.sslmit.unibo.it/]]).

However, we know little about the domains and genres of texts in corpora
collected in this way. This webpage lists resources that make I-EN, I-RU
(a web corpus of Russian) and ukWac a bit similar to the BNC.

Below I report two ways of approaching the question of genre
classification. One involves a traditional *typology* of typical genre
labels, as applicable to the Web, for example, texts aimed at
instructing, reporting or entertaining the reader. Another approach
involves designing a *topology* to assess how similar individual texts
are to a prototypical webpage, for example, a typical news item is aimed
at reporting, but some of them also aim at entertaining, so that such
texts are positioned between reporting and entertaining texts.

** Topology for text classification
   :PROPERTIES:
   :CUSTOM_ID: topology-for-text-classification
   :END:
The topological approach is described in my forthcoming paper:

Serge Sharoff, (2018) Functional Text Dimensions for annotation of Web
corpora. In /Corpora/, *31*:2 [[file:/publications/2018-ftd.pdf][PDF]]

The automatic classification model is based on a pre-trained transformer as hosted on HuggingFace: [[https://huggingface.co/ssharoff/genres]].

In the end the Web corpora can be classified to provide data on their
composition:

1. [[file:tfhub-bnc.pred.xz][BNC]]. The BNC is NOT a Web corpus. However, it is useful to compare the Web corpora to its composition.
2. [[file:thub-enmaius.genres.xz][Aranea English]]
3. [[file:thub-rumaius.genres.xz][Aranea Russian]]
4. [[file:ententen.pred.genres.xz][English TenTen]]

The training resources consist in multi-annotated webpages for Russian
and English (along with translations of some pages into Chinese, French
and German) as described in the following table:

| Corpus          | Language       | #Docs | #Words  | Annotations                                           |
| 5g, part1       | en,de,fr,ru,zh | 113   | 306302  | [[file:reference/5g-p1.tgz][5g-p1.tgz]]               |
| 5g, part 2      | en,fr,ru,zh    | 133   | 505468  | [[file:reference/5g-p2.tgz][5g-p2.tgz]]               |
| ukWac, random   | en             | 257   | 211549  | [[file:reference/ukwac-sample.tgz][ukwac-sample.tgz]] |
| GICR, random    | ru             | 618   | 919972  | [[file:reference/gicr-random.tgz][gicr-random.tgz]]   |
| GICR, blogs     | ru             | 285   | 83829   | [[file:reference/gicr-blogs.tgz][gicr-blogs.tgz]]     |
| Total           |                | 1406  | 2027120 |                                                       |
| All in one-line | en             | 1686  | 2469295 | [[file:en.ol.xz]]                                     |
| All in one-line | ru             | 1930  | 2413675 | [[file:ru.ol.xz]]                                     |

** Typology for text classification
   :PROPERTIES:
   :CUSTOM_ID: typology-for-text-classification
   :END:
The typology and the procedure for automatic annotation of Web texts is
described in:

Serge Sharoff, In the garden and in the jungle: comparing genres in the
BNC and Internet. In
[[http://www.springer.com/computer/ai/book/978-90-481-9177-2][Genres on
the Web]], Mehler, A., Sharoff., S., Santini, M., (editors)
Springer 2010. [[/serge/publications/2010-chp7-genres-web1.pdf][PDF]]

According to this approach, the texts in I-EN, I-RU and ukWac have been
automatically classified using the following classes:

1. discussion - all texts expressing positions and discussing a state of
   affairs
2. information - catalogues, lists (mostly containing incomplete
   sentences)
3. instruction - how-tos, FAQs, tutorials
4. propaganda - adverts, political pamphlets
5. recreation - fiction and popular lore
6. regulations - laws, small print, rules
7. reporting - newswires and informative broadcasts, police reports

** Source data
   :PROPERTIES:
   :CUSTOM_ID: source-data
   :END:
- English sample: [[file:i-en-sample.txt.gz]]
- Russian sample: [[file:i-ru-sample.txt.gz]]
- English POS trigrams: [[file:i-en.fw]]
- Russian POS trigrams: [[file:i-ru.fw]]

** Validated samples
   :PROPERTIES:
   :CUSTOM_ID: validated-samples
   :END:
- English BNC: [[file:bnc-coded.csv]]
- English Internet: [[file:i-en-sample-coded.csv]]
- Russian Internet: [[file:i-ru-sample-coded.csv]]
- Russian RNC: [[file:rrc-x-coded.csv]]

** Classified files
   :PROPERTIES:
   :CUSTOM_ID: classified-files
   :END:
- I-EN: [[file:i-en-pred.csv.gz]]
- ukWac: [[file:ukWac-pred.csv.gz]]
- I-RU: [[file:i-ru-pred.csv.gz]]

The accuracy of this classification is about 73-84% (see the paper above
for argumentation), so you have one chance in four that a link is not of
the correct type. Let me know if you have ideas on how to improve the
accuracy.

** Legacy classes
   :PROPERTIES:
   :CUSTOM_ID: legacy-classes
   :END:
I-EN and ukWac files have been also classified using David Lee's BNC
classification (70 genres in total) and the four main genres from the
Brown corpus (press, fiction, nonfiction and misc):

- I-EN by BNC: [[file:i-en-pred-70bnc.csv.gz]]
- I-EN by Brown Corpus: [[file:i-en-pred-4bc.csv.gz]]
- ukWac by BNC: [[file:ukWac-pred-70bnc.csv.gz]]
- ukWac by Brown Corpus: [[file:ukWac-pred-4bc.csv.gz]]

The accuracy of this classification has not been validated. Presumably
it is quite low (especially for the 70-genres classification from the
BNC). I made a quick check for the genre distribution for 8310 pages
from [[http://guardian.co.uk][The Guardian]] website, which is a
newspaper, so it should be classified as 'press' according to the Brown
Corpus, but the genre of feature articles, biographies, reviews can be
different from what is assumed by `press' in the Brown Corpus (it
corresponds to 'reporting' in the classification used above):

| 10.01% | fiction    |
| 29.07% | misc       |
| 16.68% | nonfiction |
| 44.24% | press      |

The following is the distribution of genres assigned to the same set of
8310 pages according to the BNC-trained classifier (only the 10 most
frequent labels are listed):

| 3.14%  | W_newsp_other_social         |
| 3.21%  | W_newsp_brdsht_nat_editorial |
| 3.29%  | S_speech_unscripted          |
| 3.35%  | W_newsp_brdsht_nat_commerce  |
| 3.61%  | W_newsp_brdsht_nat_sports    |
| 4.16%  | W_fict_prose                 |
| 5.57%  | W_pop_lore                   |
| 5.93%  | W_newsp_brdsht_nat_arts      |
| 6.45%  | W_biography                  |
| 8.19%  | W_newsp_brdsht_nat_misc      |
| 11.01% | W_misc                       |

Not all items are treated as coming from newspapers, but many of them
are (in the BNC genre scheme, =brdsht_nat= means `national broadsheets',
=newsp_other= means either regional or tabloid). Webpages automatically
classified as all forms of =W_newsp= account for 41% of The Guardian
subcorpus in ukWac.

** About
   :PROPERTIES:
   :CUSTOM_ID: about
   :END:
The resources listed on this page have been developed by Serge Sharoff
(Centre for Translation Studies, University of Leeds). Get in touch
[[/serge/][with me]] if you have any comments or suggestions.

*/Note: for files from the `Genres on the Web' colloquium (2007), see
the original [[file:colloquium/][colloquium page]]/*

*/Note: for the description of a Google Research Award project, see
[[file:google.html][the project webpage]]/*

\\

--------------

Serge Sharoff 2015-12-20
