#+TITLE: iDEM: Innovative and Inclusive Democratic Spaces for Deliberation and Participation
#+AUTHOR: Serge Sharoff
#+DATE: 2024-2026
#+OPTIONS: toc:nil
#+LATEX_HEADER: \usepackage{times}
#+LATEX_HEADER: \usepackage{apalike}
#+HTML_HEAD_EXTRA: <style>*{font-size: large;}</style>

 + Project Co-Ordinator :: Horacio Saggion, Universitat Pompeu Fabra (UPF)
 + Principal Investigator at Leeds :: Serge Sharoff
 + Co-Investigator at Leeds :: Carlo Eugeni
 + Funding ::  EU Horizon
 + Time frame :: 2024-2026

* Overall project aims
iDEM aims at addressing the linguistic  barriers in deliberative and participatory
democratic practices through a thorough intersectional analysis of
conditions under which the existing structures of power limit
participation of marginalised and vulnerable communities who might have
limited skills in reading, writing or understanding a fairly complex
language required for deliberative and participatory processes. Our
vision in this project is to improve this situation by developing
artificial intelligence and natural language processing models
to make democratic spaces more inclusive and accessible for all. The
democratic spaces to be proposed and implemented in realistic use cases
will allow debate between different sectors of the society. This will be
the first study to investigate artificial intelligence and natural
language processing methods as enablers in addressing political
inequality for deliberation and participation in democratic spaces.

* Our specific aims in WP3
The University of Leeds leads WP3, Advanced Human Language Technology for non-discriminatory and inclusive democratic spaces
  
This WP will research, develop and deliver the iDEM text simplification system and services. This will include investigating mechanisms:

 1. to identify complex linguistic phenomena in the specific context of the project,
 2. to implement automatic transformation aiming at reducing the complexity of the information presentation making it more accessible to specific audiences,
 3. to implement a text generation assistant in the content of deliberative democracy, and
 4. to integrate the components into an open-API cloud-based web-services platform to deliver the iDEM services and Text-simplification App.

The WP will apply Deep Learning techniques to make the methods applicable to a range of different audiences, languages and domains. The solutions (algorithms and language resources) will be implemented as a freely available library for easy integration into Internet-based deliberative and participatory democratic spaces.

  + T3.1 :: Text Difficulty Assessment and Classification Tool.
    *M1-M30.* Lead: UOLeeds. Participants: UPF, CAPITO
  + T3.2 :: Multilingual Adaptable Text Simplification System.
    *M1-M30.* Lead: UPF. Participants: UOLeeds, CAPITO
  + T3.3 :: Intrinsic and Expert Evaluation.
    M6-M31. Lead: CAPITO, Participants: UOLeeds, UPF, ANFFAS, PIM, IMPD
  + T3.4 :: Text Generation Assistant.
    M12-M34. Lead: UPF, Participants: PIM, ANFFAS, IMPD, UOLeeds
  + T3.5 :: Service Implementation.
    M6-M36. Lead: MAC. Participants: CAPITO, UOLeeds, UPF


* Participants
| *Participant organisation name*                                                   | *Country* |
| (Coordinator) Universitat Pompeu Fabra (UPF)                                      | ES        |
| University of Leeds (UOL)                                                         | UK        |
| CFS GmbH (CAPITO)                                                                 | AT        |
| NEXUS INSTITUT FUR KOOPERATIONS MANAGEMENT UND                                                  | DE        |
|  INTERDISZIPLINARE FORSCHUNG GMBH (NEXUS)                                                            |           |
| Organización de entidades en favor de las personas con                            | ES        |
| Discapacidad Intelectual de la Comunidad de Madrid (Plena Inclusión Madrid) (PIM) |           |
| The National Microelectronics Applications Centre Ltd (MAC)                       | IE        |
| Anffas Nazionale (ANFFAS)                                                         | IT        |
| Fundación Cibervoluntarios (CIB)                                                  | ES        |
| Actionaid International Italia Onlus (AAIT)                                       | IT        |
| Institut Municipal de Persones amb Discapacitat (IMPD)                            | ES        |
| Sindicatura de Greuges de Barcelona (Barcelona Ombudsman's Office)                                    | ES        |


  
